# Generated by Django 5.2.15 on 2026-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_editora_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=18)),
            ],
        ),
    ]
